baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LanceDB Blog'

# Pagination settings (updated for Hugo v0.147.7+)
[pagination]
pagerSize = 9
path = "page"

# Taxonomy Configuration
[taxonomies]
category = "categories"

# Category Configuration
[params]
categories = [
    { name = "Engineering", slug = "engineering", description = "Technical deep dives, architecture insights, and engineering solutions" },
    { name = "Case Study", slug = "case-study", description = "Real-world implementations and customer success stories" },
    { name = "Announcement", slug = "announcement", description = "Product updates, releases, and company news" }
]

# Table of Contents Configuration
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
    
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
