baseURL = 'https://lancedb.com'
languageCode = 'en-us'
title = 'LanceDB Blog'

relativeURLs = true
canonifyURLs = true

# Build settings
buildFuture = true

# Pagination settings
[pagination]
pagerSize = 9
path = "page"

# Permalinks Configuration
[permalinks]
blog = "/:filename/"

# Taxonomy Configuration
[taxonomies]
category = "categories"

# Category Configuration
[params]
mainLanceDBURL = "http://lancedb-website-staging.s3-website-us-east-1.amazonaws.com"
cloudLanceDBURL = "https://cloud.lancedb.com"
privacyPdfURL = "https://lancedb.com/docs/LanceDB%20Privacy%20Policy.pdf"
termsPdfUrl = "https://lancedb.com/docs/LanceDB%20Cloud%20Terms%20of%20service.pdf"
discordURL = "https://discord.com/invite/G5DcmnZWKB"
supportURL = "mailto:support@lancedb.com"
githubURL = "https://github.com/lancedb"
linkedInURL = "https://www.linkedin.com/company/lancedb/"
xURL = "https://x.com/lancedb"

categories = [
    { name = "Engineering", slug = "engineering", description = "Technical deep dives, architecture insights, and engineering solutions" },
    { name = "Case Study", slug = "case-study", description = "Real-world implementations and customer success stories" },
    { name = "Announcement", slug = "announcement", description = "Product updates, releases, and company news" }
]

# Table of Contents Configuration
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
    
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

  # Syntax Highlighting Configuration
  [markup.highlight]
    style = "github-dark"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    hl_inline = false
    anchorLineNos = false
    lineAnchors = ""
    tabWidth = 2
